version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks:
      - backend

  bot:
    build: .
    environment:
      - API_PATH=http://web:8000
    command: python bot/bot.py
    networks:
      - backend
    depends_on:
      - web

networks:
  backend:
